version: 2
jobs:
  build:
    docker:
      - image: docker:19.03
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login
          command: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
      - run:
          name: Build
          command: ./build.sh
      - run:
          name: Push
          command: ./push.sh
workflows:
  version: 2
  generate_and_build:
    jobs:
      - build:
          filters:
            branches:
              only: master

